run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable:
      - shadow

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - goimports
      text: "File is not `goimports`-ed"
